@startuml

[*] --> LookingForAllRequirements

LookingForAllRequirements --> LookingForCapitalLetter: [!@#$%&*]
LookingForAllRequirements --> LookingForSpecialCharacter: [A-Z]
LookingForAllRequirements --> LookingForAllRequirements: anything else

LookingForCapitalLetter --> Valid: [A-Z]
LookingForCapitalLetter --> LookingForCapitalLetter: anything else

LookingForSpecialCharacter --> LookingForNonSpecialCharacter: [!@#$%&*]
LookingForSpecialCharacter --> LookingForSpecialCharacter: anything else

LookingForNonSpecialCharacter --> LookingForNonSpecialCharacter: [!@#$%&*]
LookingForNonSpecialCharacter --> Valid: anything else

Valid --> [*]
Valid --> Valid: anything else
Valid --> Invalid: [!@#$%&*]

Invalid --> Valid: anything else

@enduml