@startuml

[*] --> LookingForDigit
LookingForDigit --> Integer: [1-9]
LookingForDigit --> NotInteger: anything else
Integer --> Integer: [0-9]
Integer --> [*]
Integer --> NotInteger: anything else
NotInteger --> [*]

@enduml