@startuml

[*] --> LookingForDigit
LookingForDigit --> Integer: [1-9]
LookingForDigit --> Error: anything else
Integer --> Integer: [0-9]
Integer --> [*]
Integer --> Error: anything else
Error --> [*]

@enduml